CREATE TABLE RVAP_ROLES (
	ID_ROL INT,
	COD_ROL VARCHAR(5) UNIQUE,
	DESCRIPCION VARCHAR(25),
	CONSTRAINT PK_ROL PRIMARY KEY(ID_ROL)
);

CREATE TABLE RVAP_USUARIOS (
	ID_USUARIO INT,
	NIF VARCHAR(10),
	NOMBRE VARCHAR(50),
	APELLIDO1 VARCHAR(50),
	APELLIDO2 VARCHAR(50),
	EMAIL VARCHAR(50),
	COD_ROL VARCHAR(5),
	CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO),
	CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (COD_ROL) REFERENCES RVAP_ROLES (COD_ROL)
);


CREATE TABLE RVAP_CIUDAD (
	ID_CIUDAD INT,
	NOMBRE VARCHAR(50),
	CODIGO VARCHAR(5),
	FECHA_BAJA DATE,
	CONSTRAINT PK_CIUDAD PRIMARY KEY (ID_CIUDAD)
);

CREATE TABLE RVAP_OFICINA (
	ID_OFICINA INT,
	ID_CIUDAD INT,
	NOMBRE VARCHAR(50),
	DIRECCION VARCHAR(75),
	URL_MAPS_OFICINA VARCHAR(500),
	FECHA_BAJA DATE,
	CONSTRAINT PK_OFICINA PRIMARY KEY (ID_OFICINA),
	CONSTRAINT FK_CIUDAD_OFICINA FOREIGN KEY (ID_CIUDAD) REFERENCES RVAP_CIUDAD (ID_CIUDAD)
	
);

CREATE TABLE RVAP_PLANTA (
	ID_PLANTA INT,
	ID_OFICINA INT,
	NOMBRE VARCHAR(50),
	NUM_PLANTA VARCHAR(10),
	PLANO_PLANTA BLOB,
	NUMERO_DE_SITIOS INT,
	QR_AUTO_RESERVA BLOB,
	FECHA_BAJA DATE,
	CONSTRAINT PK_PLANTA PRIMARY KEY (ID_PLANTA),
	CONSTRAINT FK_OFICINA_PLANTA FOREIGN KEY (ID_OFICINA) REFERENCES RVAP_OFICINA (ID_OFICINA)
);

CREATE TABLE RVAP_SITIO (
	ID_SITIO INT,
	ID_PLANTA INT,
	ID_OFICINA INT,
	NUMERO_SITIO INT,
	FECHA_BAJA DATE,
	CONSTRAINT PK_SITIO PRIMARY KEY (ID_SITIO),
	CONSTRAINT FK_PLANTA_SITIO FOREIGN KEY (ID_PLANTA) REFERENCES RVAP_PLANTA (ID_PLANTA),
	CONSTRAINT FK_OFICINA_SITIO FOREIGN KEY (ID_OFICINA) REFERENCES RVAP_OFICINA (ID_OFICINA)
);

CREATE TABLE RVAP_RESERVA (
	ID_RESERVA INT,
	ID_SITIO INT NOT NULL,
	CODIGO_RESERVA VARCHAR(15),
	FECHA DATE NOT NULL,
	ID_USUARIO_RESERVA INT,
	NIF_RESERVA VARCHAR(10) NOT NULL,
	EMAIL_RESERVA VARCHAR(50) NOT NULL,
	HA_FICHADO VARCHAR(1) DEFAULT 'N',
	ANULADA VARCHAR(1) DEFAULT 'N',
	CONSTRAINT PK_RESERVA PRIMARY KEY (ID_RESERVA),
	CONSTRAINT FK_SITIO_RESERVA FOREIGN KEY (ID_SITIO) REFERENCES RVAP_SITIO (ID_SITIO),
	CONSTRAINT FK_USUARIO_RESERVA FOREIGN KEY (ID_USUARIO_RESERVA) REFERENCES RVAP_USUARIOS (ID_USUARIO)
);

CREATE TABLE RVAP_EMAILS (
	ID_EMAIL INT,
	ID_USUARIO INT,
	DESTINATARIO VARCHAR(50),
	CONTENIDO LONGTEXT,
	CONSTRAINT PK_REMAIL PRIMARY KEY (ID_EMAIL),
	CONSTRAINT FK_EMAIL_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES RVAP_USUARIOS (ID_USUARIO)
);