logging:
  level:
    .: INFO
    org.springframework: INFO
    com.victorb: INFO
    


spring:
  config:
    activate:
      on-profile: local

  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.1.215:3306/RESERVAPP
    username: RVAP_USR
    password: RVAP_USR
  
  jpa:
    show-sql: true
    properties:
      hibernate: 
        ddl-auto: none
        dialect: org.hibernate.dialect.MariaDBDialect
      
security:
  jwt:
    duration: 1440 #En minutos, 24 horas
    secret: 1w4eqvrR7d3eUr2oOUL5JVqMGVkjbFtuYC1AlF2B6OSKE32W #Secret en base64 distintos para cada entorno para que no sirva el token de uno en otro
    
server:
  servlet:
    context-path: /rvap

--- 
logging:
  level:
    .: ERROR
    org.springframework: ERROR
    com.victorb: INFO
    
security:
  jwt:
    duration: 60 #En minutos, 1 hora
    secret: mE189/l9Ne+mFY2An9oR/40aiREViUC9Zl/gn668kZcFNUom #Secret en base64 distintos para cada entorno para que no sirva el token de uno en otro

spring:
  config:
    activate:
      on-profile: pro
      
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.1.215:3306/RESERVAPP
    username: RVAP_USR
    password: RVAP_USR
  
  jpa:
    show-sql: false
    hibernate: 
      ddl-auto: none
      dialect: org.hibernate.dialect.MariaDBDialect
      
server:
  servlet:
    context-path: /rvap